-- database/01_schema_structure.sql

-- Extensões
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Profiles
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY,
    email TEXT,
    role TEXT DEFAULT 'user'::text,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Products
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC,
    category TEXT,
    size TEXT,
    image TEXT,
    images TEXT[] DEFAULT '{}'::text[],
    quantity INTEGER DEFAULT 0,
    stock JSONB DEFAULT '{}'::jsonb,
    is_featured BOOLEAN DEFAULT false,
    material VARCHAR(100),
    pattern VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Migração: adiciona colunas em instâncias já existentes (material, pattern)
ALTER TABLE products ADD COLUMN IF NOT EXISTS material VARCHAR(100);
ALTER TABLE products ADD COLUMN IF NOT EXISTS pattern VARCHAR(100);
-- Migração: remove color de products (passa a ser propriedade da variante)
ALTER TABLE products DROP COLUMN IF EXISTS color;

-- 2b. Product Variants (cor + tamanho + estoque por variante)
CREATE TABLE IF NOT EXISTS product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    color TEXT NOT NULL,
    size TEXT NOT NULL,
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    sku TEXT UNIQUE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_product_variants_product_color_size
    ON product_variants (product_id, color, size);

CREATE INDEX IF NOT EXISTS idx_product_variants_product_id ON product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_product_variants_sku ON product_variants(sku);

-- 3. Orders
CREATE TABLE IF NOT EXISTS orders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id),
    payment_status TEXT DEFAULT 'pending'::text,
    delivery_status TEXT DEFAULT 'pending'::text,
    total_amount NUMERIC NOT NULL,
    payment_method TEXT,
    payment_id TEXT,
    mp_payment_id TEXT,
    payer JSONB DEFAULT '{}'::jsonb,
    installments INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Migração: renomeia status legado para payment_status (quando existir)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'orders'
          AND column_name = 'status'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'orders'
          AND column_name = 'payment_status'
    ) THEN
        ALTER TABLE orders RENAME COLUMN status TO payment_status;
    END IF;
END $$;

-- Migração: garante colunas novas em instâncias já existentes
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'pending'::text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_status TEXT DEFAULT 'pending'::text;

-- 4. Order Items
CREATE TABLE IF NOT EXISTS order_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    price NUMERIC NOT NULL,
    price_at_purchase NUMERIC,
    image_url TEXT,
    color TEXT,
    size TEXT
);

ALTER TABLE order_items ADD COLUMN IF NOT EXISTS color TEXT;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS size TEXT;

-- 5. Vouchers (cupom de desconto: código 5 caracteres, validade)
CREATE TABLE IF NOT EXISTS vouchers (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    amount NUMERIC NOT NULL,
    order_id UUID REFERENCES orders(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    valid_until TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE
);

-- 6. Order Refunds (solicitações de cancelamento/reembolso e reembolsos backoffice)
CREATE TABLE IF NOT EXISTS order_refunds (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    request_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    refund_method TEXT,
    amount NUMERIC NOT NULL,
    order_item_ids UUID[] DEFAULT '{}',
    mp_refund_id TEXT,
    voucher_id UUID REFERENCES vouchers(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Índices (products)
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_vouchers_code ON vouchers(code);
CREATE INDEX IF NOT EXISTS idx_vouchers_valid_until ON vouchers(valid_until);
CREATE INDEX IF NOT EXISTS idx_order_refunds_order_id ON order_refunds(order_id);

-- Migração: dados de pagamento PIX/boleto para o usuário copiar (quando pendente)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_code TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_url TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_expiration TIMESTAMP WITH TIME ZONE;

-- Migração: fulfillment / rastreamento Melhor Envio
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tracking_code TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_service TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_amount NUMERIC;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS melhor_envio_order_id TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_agency_id INTEGER;

-- Índices para correlação e consultas de frete/webhook
CREATE INDEX IF NOT EXISTS idx_orders_melhor_envio_order_id ON orders(melhor_envio_order_id);
CREATE INDEX IF NOT EXISTS idx_orders_tracking_code ON orders(tracking_code);